### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by BrandonSurowiec** [Gargron/fileupload#18]
Last release was Feb 2014. There have been a lot of commits since then and I'm currently using `dev-master` in my composer file. Is there something else that needs to be done before next release?

**Comment by HMAZonderland** [comment]
Perhaps send the guy an e-mail?

**Comment by Gargron** [comment]
Sorry, got caught up in other projects. It's gotta be said, there were a lot of commits but not a lot has changed functionally. Bumped up the tag to 1.1.0

**Comment by BrandonSurowiec** [comment]
Thank you!
