### ISSUE TITLE
Error on Using FileNameGenerator\MD5()

### ISSUE THREAD

**Issue by ghost** [Gargron/fileupload#23]
![error](https://cloud.githubusercontent.com/assets/17355405/13372036/50573796-dd5c-11e5-90fa-641fa452ae93.png)

Error on Using  _FileNameGenerator\MD5()_ because *_Simple *_ is already in use

**Comment by Gargron** [comment]
My question is, why is the validator required from that class? And why is it a specific one rather than the Validator interface? I feel like that line could be removed altogether. Must be from one of the pull requests...

**Comment by pranit113** [comment]
Yes. You're right :+1:
