### ISSUE TITLE
Invalid $files after processAll()

### ISSUE THREAD

**Issue by ghost** [Gargron/fileupload#25]
`list($files, $headers) = $fileupload->processAll();
`

While uploading multiple image files, the $files array I received was wrong.
It had the same value (last image data) for all array indices.

Can anyone please confirm if this is the case with everyone or just me ?

_In case it's for everyone, this is a major issue and I have found a solution which I would be happy to share._

**Comment by andrew951** [comment]
I am also experiencing this issue. What is the solution that you've found?

**Comment by pranit113** [comment]
_src/FileUpload/FileUpload.php_

_Line 281_

$files is a protected array of Class FileUpload. While pushing array into $files this roughly what happened

```
$files[] = $this->process // Returns file object instance 1
echo $files; // files ( 0 => object 1 )

$files[] = $this->process // Reurns file object instance 2
echo $files; // files ( 0 => object 2,    1 => object 2 )
```

It changed all the values to the last object instance value.

**Solution.**

_On Line 281_

`$this->files[] = (object)(array)$this->process( ...`

Type cast the object to array, and then again to object. This way the values were retained, and not replaced.

Let me know if it worked for you too.

**Comment by kaperys** [comment]
Worked for me. Created a PR https://github.com/Gargron/fileupload/pull/28
