### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by radovangardic** [Gargron/fileupload#29]
How do I pass in a name manually ?
Example: If I want the new file to be named "newFileName1", and not have it generate a random string with FileNameGenerator (Simple or MD5).

**Comment by adelowo** [comment]
Hi @radovangardic This feature is now available in the `master` branch. It hasn't been tagged though. Can you test this out ?

**Comment by adelowo** [comment]
This has been tagged [ 1.2.0]. Would have to close this issue.

**Comment by radovangardic** [comment]
I tested it, and it's perfect! Thank you.

I'm sorry I didn't test it earlier, but I had personal problems and I
wasn't checking my email up until now.

**Comment by adelowo** [comment]
Thanks a lot
