### ISSUE TITLE
PHP 7.1 incompatibility

### ISSUE THREAD

**Issue by radmax** [Gargron/fileupload#32]
Due change in handling strings in PHP 7.1

> New E_WARNING and E_NOTICE errors have been introduced when invalid strings are coerced using operators expecting numbers (+ - * / ** % << >> | & ^) or their assignment equivalents. An E_NOTICE is emitted when the string begins with a numeric value but contains trailing non-numeric characters, and an E_WARNING is emitted when the string does not contain a numeric value.

There is now E_NOTICE in function [getConfigBytes](https://github.com/Gargron/fileupload/blob/master/src/FileUpload/FileUpload.php#L489-L504). `$val` variable has to be stripped of last character (k, M, etc.) to be valid for numeric computations.

**Comment by adelowo** [comment]
I haven't upgraded to 7.1 yet (still on 7.0) but i can see this [here](http://php.net/manual/de/migration71.other-changes.php). Thanks
