### ISSUE TITLE
How to detect validation errors?

### ISSUE THREAD

**Issue by kwebble** [Gargron/fileupload#44]
I'm evaluating this component and would like to know how code should determine if an upload was skipped and get the error that the validator detected?

In the returned files array `error` and `errorCode` are always 0, even when a validator determined that an upload is invalid.

I saw `FileUpload::process()` returns a new `File` instance. This object does not include the error detected during processing.

**Comment by adelowo** [comment]
Sorry for the late response. 

I don't get this, i get the error messages if an upload fails. Below is a snapshot. 

![screenshot from 2017-02-20 09 04 44](https://cloud.githubusercontent.com/assets/12677701/23116648/ec816fec-f74b-11e6-8016-eac7030f338f.png)

As an aside, what validator are you making use of ?

**Comment by adelowo** [comment]
I'd like to clear this issue out as quick as possible as it seems to be the only reason i haven't pushed a new tag from the `hot-fix` branch

**Comment by kwebble** [comment]
You don't have to wait on me for tagging, perhaps I'm misunderstanding something.

And I already added some validation outside this component to handle the situation in my project.

**Comment by kwebble** [comment]
I investigated some more and now think the problem is caused by #37. The result is an initial `$fileInfo` based on an empty `$file_path`.

**Comment by adelowo** [comment]
@kwebble , you make use of a custom validator ? I wanted to ask if you were setting the error message after a failed validation (https://github.com/Gargron/fileupload/blob/master/src/FileUpload/Validator/MimeTypeValidator.php#L54-L56) but since you mentioned #37 is the case - the reporter also says ___the fix works___- . Lemme push those changes.

**Comment by adelowo** [comment]
I have done that already, you can test to make sure it works.. Tag version is 1.4.1

**Comment by kwebble** [comment]
Tested and got an error message if validation fails, nice!

**Comment by adelowo** [comment]
Awesome then

**Comment by adelowo** [comment]
Since this is marked as fixed, i am closing this
