### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by patrickschmidt** [Gargron/fileupload#47]
I am getting the following two warnings when I upload chunked files

`Notice: Undefined variable: completed in [...]/vendor/gargron/fileupload/src/FileUpload/FileUpload.php on line 360`

`Notice: Undefined property: FileUpload\File::$size in [...]/vendor/gargron/fileupload/src/FileUpload/FileUpload.php on line 579`

Cheers,
Patrick.

**Comment by adelowo** [comment]
What release are you making use of ? I want to believe this doesn't exists in the latest release  1.4.1

**Comment by patrickschmidt** [comment]
I use version v1.4.1

Variable `$completed`  is only set if `$file->size == $file_size` due to line 345. Which is not true in chunked uploads.

In line 359 a new `File` object is instantiated and member variable `size` is not assigned after that.

Maybe that helps.

**Comment by adelowo** [comment]
@patrickschmidt sorry for the last response, I'd push a fix tomorrow

**Comment by adelowo** [comment]
*late*

**Comment by adelowo** [comment]
@patrickschmidt can you try out the `hot-fix` branch .. https://github.com/Gargron/fileupload/commit/b3126e08c56a131153e8c08353947aea4b0b694a

**Comment by Paradinight** [comment]
Small typo in the fix.
On line 310 $complteted = false; to $completed = false;

The mime type validation does not work if i use the chunked file upload. Without the the mime_type validation the fix work :)

Fixing the mime type validation is hard. finfo_file only works if the upload is completed.

**Comment by adelowo** [comment]
Oops, thanks a lot.. I switched to sublime text, phpstorm would have alerted me of a typo.. Would fix that. 

THanks for testing it, I would tag a new version. 

As per the mime type validation, that would be pretty hardcore to tackle.

**Comment by adelowo** [comment]
Just merged in #48 and i tagged `1.4.2` . 

Thanks a lot
