### ISSUE TITLE
the call of the processCallbacksFor for completed is in the wrong place

### ISSUE THREAD

**Issue by Paradinight** [Gargron/fileupload#49]
the call of the processCallbacksFor for completed is in the wrong place.

https://github.com/Gargron/fileupload/blob/master/src/FileUpload/FileUpload.php#L349

should be
`$file = new $file($file_path);
$file->completed = $completed;
$file->size = $file_size;
if($completed === true)
{
    $this->processCallbacksFor('completed', $file);
}
`
the first version show the tmp file not the real file

**Comment by adelowo** [comment]
Whoops, i didn't review properly after i added `\SplfileInfo`.. Thanks a lot, i have fixed that in https://github.com/Gargron/fileupload/commit/5e34ab9780c2a989fd4b6152b212c136c678e64f

**Comment by Paradinight** [comment]
Thank :)

**Comment by adelowo** [comment]
You welcome 👍
