### ISSUE TITLE
Enhancement: FileNameGenerator\Hash

### ISSUE THREAD

**Issue by Indigo744** [Gargron/fileupload#54]
If I may suggest a nice enhancement.

Get rid of `FileNameGenerator\MD5` class and add a `FileNameGenerator\Hash` class which accept:
1.  A hashing algorithm name, as expected by the `hash()` function ([PHPDoc](http://php.net/manual/en/function.hash.php)), and as listed by `hash_algos()` ([PHPDoc](http://php.net/manual/en/function.hash-algos.php))
2. An optional salt string, for avoiding collision attack (e.g. in case the hashed name is made public)
3. An optional allowOverride boolean

This will allow a lot more flexibility. What do you think?

**Comment by adelowo** [comment]
Nice suggestion... I should work on it.. 

But i think it is just safer to mark the `MD5` class as deprecated instead

**Comment by adelowo** [comment]
Update --> I feel this is just too much work to be added to the library and feels kind of better having users do something like this themselves..
