### ISSUE TITLE
get the file name

### ISSUE THREAD

**Issue by blsn** [Gargron/fileupload#59]
`list($files, $headers) = $fileupload->processAll();`
`echo json_encode(['files' => $files]);`

Two files were uploaded.
file **name** visible only for validation file error: 

`{"files":[{"error":"Filetype not allowed","errorCode":0,"completed":false,"name":"header-image.jpg","size":72193},{"error":0,"errorCode":0,"completed":true,"size":2254}]}
`

How to get the file name?

**Comment by adelowo** [comment]
```php
list($files, $headers) = $fileUpload->processAll();

foreach ($headers as $header => $value) {
    header($header . ': ' . $value);
}

foreach($files as $file) {
    //Regardless of the validation status - failed or not you do this
    echo $file->getFilename();
}
```

**Comment by blsn** [comment]
Adding the '`foreach`' loop after `processAll()` as suggested, doesn't give this key ('`name`').
