### ISSUE TITLE
Multiple upload

### ISSUE THREAD

**Issue by iyasilias** [Gargron/fileupload#60]
I've seen closed issue with the same title, but it seems no one have problems uploading multiple files.

I'm pretty sure HTML doesn't require a name with `[] `such as `files[]` in this sample code` <input class="form-control" type="file" name="files[]" value="" multiple/>` if we want to upload multiple files.

Just to point out that there is no where in your docs stating the need for an `[]`.

Great library though. Thumbs up!

**Comment by iyasilias** [comment]
Additional question, how do I name my file based on files count? Like note1.pdf, note2.pdf if 2 pdf files uploaded?

**Comment by adelowo** [comment]
This cannot be done by the library currently.. A method you can use to do this is to use the `completed` callback.. Basically, you rename the files .  

Another method you can for this (although kind of a hack) is to create a custom name generator class that has state. The generator should have a counter property that denotes the number of uploaded files, then you just append the counter value to the filename.
