### ISSUE TITLE
file name of upload completed 

### ISSUE THREAD

**Issue by blsn** [Gargron/fileupload#61]
#59 
```
list($files, $headers) = $fileupload->processAll();
echo json_encode(['files' => $files]);
```

Two files were uploaded.
file name visible only for validation file error:

`{"files":[{"error":"Filetype not allowed","errorCode":0,"completed":false,"name":"header-image.jpg","size":72193},{"error":0,"errorCode":0,"completed":true,"size":2254}]}`

This will work only as follows:

```
        foreach($files as $file) {
            if ($file->completed) { // check if the upload was completed
                echo $file->getFilename();
            }
        }       
```
But how can I get the file names for both completed/uncompleted?

**Comment by adelowo** [comment]
@blsn Oh, I get that, I still get the file name for uncompleted uploads but it is the name as stored in the temporary directory (by PHP), something like `PHPjks` . The generated name (by the library) only works for completed files.  Is there any reason you are trying to get the filename for uncompleted uploads ? 

Pls let me know your reasoning. I would take a look at this tomorrow

**Comment by blsn** [comment]
To provide the user with a notification about the uncompleted file name beside the error message accordingly. 

This feature is very important.
