### ISSUE TITLE
Store the original file name in File class

### ISSUE THREAD

**Issue by fansanelli** [Gargron/fileupload#66]
I could implement the feature in subject, but before I'd like to hear some feedback... I'm using the random name generator, but I still need the original file name. To workaround the lack of this feature I am looping files array returned by processAll() method while reading the value from the global one: $_FILES['foo']['name'][$i]. What do you think?

**Comment by adelowo** [comment]
That is totally fine... Do you want to do this. You can just expose a method like `getClientOriginalName` or something .. Thanks for #65 anyways

**Comment by adelowo** [comment]
Closed by #67
