### ISSUE TITLE
add base64 functonality

### ISSUE THREAD

**Issue by jackttcoms** [Gargron/fileupload#73]
Hi, amazing class.

Is it possible to add base64 decode in the future to make it compatible with Croppie.js or is there a way i can use this script and do the decoding i would love to know.

Also another idea could be a watermark functionality.

Thanks. Amazing class!

**Comment by adelowo** [comment]
Hi, thanks for dropping your thoughts here. I will take a look at croppie JS and update this issue. 

Thanks

**Comment by jackttcoms** [comment]
Ok thanks. Also how do i use this alongside other form elements such as an input for a name and a textarea?

Thanks

**Comment by adelowo** [comment]
Hi,

this is in no way related to this library as that is an HTML thing but anyways, it is 
the same standard file  input field you will need to make use of 
`<input type="file" name="someidentifier />`

I haven't had the time to look at croppie but this library currently has no plans to support base64 decoding. Send the cropped image as you'd regularly do with HTML input tags. 

I will also be closing this issue but this feature will be reviewed again if someone 
sends a PR to support base64 decoding
